-- AlterTable
ALTER TABLE "hospital_config" ADD COLUMN     "appointment_reminders" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "backup_frequency" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "data_retention_days" INTEGER NOT NULL DEFAULT 2555,
ADD COLUMN     "default_language" TEXT NOT NULL DEFAULT 'en',
ADD COLUMN     "default_payment_terms" TEXT,
ADD COLUMN     "doctor_consultation_duration" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "email_notifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "emergency_contact" TEXT,
ADD COLUMN     "enable_data_backup" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "license_number" TEXT,
ADD COLUMN     "postal_code" TEXT,
ADD COLUMN     "privacy_policy_url" TEXT,
ADD COLUMN     "registration_number" TEXT,
ADD COLUMN     "sms_notifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "state" TEXT,
ADD COLUMN     "terms_of_service_url" TEXT,
ADD COLUMN     "test_result_notifications" BOOLEAN NOT NULL DEFAULT true;
